
import { Inter } from 'next/font/google'
import "./styles/all.scss"
import "./styles/main.scss"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Eco Orbit',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" as="style" href="./assets/" />
      </head> 
      <body  className={inter.className}>{children}</body>
    </html>
  )
}
